### ISSUE TITLE
První úkol

### ISSUE THREAD

**Issue by Martina-Kor** [Martina-Kor/Python1-spring-2022#1]
Ahoj Anet,

posílám řešení prvního úkolu a testuji spojení :-).

Zítra bohužel se hodiny nezúčastním, nevíš, jestli a komu to mám omlouvat předem?

Hezký začátek týdne,

Martina

**Comment by Martina-Kor** [comment]
Prosím o potvrzení, že spojení funguje.

**Comment by AnetaPopelova** [comment]
Ahoj, spojeni funguje :-)

Bude super, kdyz k issue vzdy pridas i odkaz na soubor s ukolem, at se v tom cesem neztratime :-)
Viz https://github.com/Martina-Kor/Python1-spring-2022/blob/main/ukol1.py

Tvuj kod bohuzel nekontroluje, jestli byl balik predan kyrurovi (true / false), jen jestli je cislo baliku ve slovniku. 
Zkus to jeste upravit, aby vracel jiny text pri true a jiny pri false. 
Pro kontrolu klice muzes pouzit` baliky[code_of_parcel]`. 

Ohledne dochazky bude nejlepsi domluvit se na Slacku, jak jsi to uz udelala.

**Comment by Martina-Kor** [comment]
Ahoj Anet, takže issue není nijak spojeno s tím py souborem? Ok, příště
přidám odkaz.
Díky za upřesnění zadání, máš pravdu, došlo mi to až teď. Jak se dostat k
true a false vím, akorát jsem nějak nepochopila, k čemu by to bylo... já
vlastně dala všem balíkům true... upravím, akorát dřív jak zítra večer se k
tomu nedostanu. ¨
Díky.

M.

**Comment by Martina-Kor** [comment]
Ahoj Anet,

tak ještě jednou, snad už lépe. Akorát nevím, jak ses dostala k tomu odkazu Ty, ten můj vypadá úplně jinak... Poradíš mi prosím?
https://github.com/Martina-Kor/Python1-spring-2022/commit/a0590cc4a83c59ade64e2f7222fcdc504fc3a9b8

Díky moc,

Martina

**Comment by AnetaPopelova** [comment]
Nejjednodusi je jen zkopirovat URL z prohlizece. Nebo skrz tri tecky viz screen. 
<img width="1248" alt="Screenshot 2022-03-08 at 17 19 56" src="https://user-images.githubusercontent.com/47115025/157280081-78775464-471a-453d-a291-93131f93991d.png">

**Comment by AnetaPopelova** [comment]
Jinak super, i to pridani kontroly, jestli je balik vubec v systemu 👍

(Jo a ten tvuj odkaz vedl na prehled zmen, ktere se staly mezi poslednim a predposlednim commitem - obcas to muze byt uzitecne.)
