### ISSUE TITLE
Desátý úkol

### ISSUE THREAD

**Issue by Martina-Kor** [Martina-Kor/Python1-spring-2022#10]
Ahoj Anet,

posílám odkaz na desátý úkol a prosím o kontrolu.
https://github.com/Martina-Kor/Python1-spring-2022/blob/main/10hw_city_temperature.py

Díky, Martina

**Comment by AnetaPopelova** [comment]
👍 

P.S.: pro nahled tabulek se muze hodit krome `.info()` i treba `.head()`
