### ISSUE TITLE
Second homework (states of the world)

### ISSUE THREAD

**Issue by Martina-Kor** [Martina-Kor/Python1-spring-2022#2]
Ahoj Anet,

posílám druhý úkol. Prosím Tě, je nějaký elegantní způsob, jak zjistit seznam světadílů, které můžeme zadat? Nakonec jsem použila pandas, nějak mě nenapadlo, jak to udělat, aby se mi udělal jen čistý výčet bez opakování... 
https://github.com/Martina-Kor/Python1-spring-2022/blob/main/2hw_worlds_states.py

Díky, 

Martina

**Comment by AnetaPopelova** [comment]
Tohle jsme probiraly na minule hodine... pomohlo ti to? Tady je kdyztak odkaz na [Slack](https://python-1-group.slack.com/archives/C035J6D4JK1/p1648484594238609), kde takovy kod Lida sdilela...

**Comment by Martina-Kor** [comment]
Ahoj Anet, ano, díky. M.
