### ISSUE TITLE
Tak ještě jednou, issue ke třetímu úkolu

### ISSUE THREAD

**Issue by Martina-Kor** [Martina-Kor/Python1-spring-2022#3]
Ahoj Anet, 

tak druhý pokus ke třetímu úkolu. Původně jsem myslela, že bych zkoušela hledat nějaký funkční sofistikovaný kód na opravdové ověřování funkčních telefonních čísel, ale vzdala jsem to, zabralo by mi to víc času, než toto.

https://github.com/Martina-Kor/Python1-spring-2022/blob/main/3hw_SMS_messages.py

Martina

**Comment by AnetaPopelova** [comment]
To je moc hezky kus kodu 👍 

(Ano, to co popisujes znam velmi dobre :-D )
