### ISSUE TITLE
Třetí a čtvrtý úkol

### ISSUE THREAD

**Issue by Martina-Kor** [Martina-Kor/Python1-spring-2022#4]
Divný... chtěla jsem udělat issue pro čtvrtý úkol a vyjelo mi to, co jsem napsala pro třetí, a pak jsem to nemohla najít... 

Takže ještě by tam měl být čtvrtý úkol :-).

Díky, M.

Ahoj Anet, 

posílám třetí úkol. Omlouvám se, že až tak na poslední chvíli, měla jsem pocit, že jsi mi nic ještě nepsala k druhému úkolu, takže jsem to trochu odložila. (A opravdu jsem si myslela, že se budeš teprve teď dívat na úkoly z druhého týdne, navíc opravdu vůbec nestíhám)
U telefonních čísel bych asi spíš zkoumala nějakou už vytvořenou knihovnu, která by číslo ověřila, ale to bych na to potřebovala daleko víc času, tak aspoň takto.

https://github.com/Martina-Kor/Python1-spring-2022/blob/main/3hw_SMS_messages.py

Díky,

Martina

**Comment by Martina-Kor** [comment]
link na čtvrtý úkol:
https://github.com/Martina-Kor/Python1-spring-2022/blob/main/4hw_car_registration.py

**Comment by AnetaPopelova** [comment]
Hezke! Elegantni!
